# -------------  Dockerfile --------------
FROM php:7-apache
COPY default1.conf /etc/apache2/sites-available/default1.conf
COPY files /var/www/public
RUN chown -R www-data:www-data /var/www/public
EXPOSE 80
CMD ["apache2-foreground"]